from __future__ import annotations

import re
from collections import Counter, defaultdict
from pathlib import Path

from models.code_metrics import CodeMetrics
from models.repository import Repository


class CodeExtractor:
    """
    Extracts deterministic source code metrics.

    Responsibilities
    ----------------
    - Count LOC
    - Count comments
    - Count blank lines
    - Count TODO/FIXME/HACK
    - Count classes/functions
    - Detect generated/minified files
    - Produce only metrics

    Never:
    - Scores
    - Findings
    - Recommendations
    """

    COMMENT_PREFIXES = (
        "#",
        "//",
        "--",
        ";",
        "%",
        "'",
    )

    BLOCK_COMMENT_START = (
        "/*",
        '"""',
        "'''",
    )

    BLOCK_COMMENT_END = (
        "*/",
        '"""',
        "'''",
    )

    CLASS_PATTERNS = (
        re.compile(r"^\s*class\s+\w+"),
        re.compile(r"^\s*public\s+class\s+\w+"),
        re.compile(r"^\s*private\s+class\s+\w+"),
        re.compile(r"^\s*protected\s+class\s+\w+"),
    )

    FUNCTION_PATTERNS = (
        re.compile(r"^\s*def\s+\w+\("),
        re.compile(r"^\s*async\s+def\s+\w+\("),
        re.compile(r".+\)\s*\{"),
        re.compile(r"function\s+\w+\("),
    )

    INTERFACE_PATTERN = re.compile(r"^\s*interface\s+\w+")

    ENUM_PATTERN = re.compile(r"^\s*enum\s+\w+")

    GENERATED_KEYWORDS = (
        "generated",
        "auto-generated",
        "autogenerated",
        "do not edit",
    )

    def extract(
        self,
        repository: Repository,
    ) -> Repository:

        metrics = CodeMetrics()

        self._extract_source_metrics(
            repository,
            metrics,
        )

        self._calculate_percentages(
            metrics,
        )

        repository.code_metrics = metrics

        return repository

    def _extract_source_metrics(
        self,
        repository: Repository,
        metrics: CodeMetrics,
    ) -> None:

        filename_counter = Counter()

        for file_path in repository.source_files:

            filename_counter[file_path.name] += 1

            extension = file_path.suffix.lower()

            metrics.source_file_extensions[
                extension
            ] = (
                metrics.source_file_extensions.get(
                    extension,
                    0,
                )
                + 1
            )

            contents = repository.file_contents.get(
                file_path,
                "",
            )

            self._analyse_file(
                file_path,
                contents,
                metrics,
            )

        duplicates = [
            name
            for name, count in filename_counter.items()
            if count > 1
        ]

        metrics.duplicate_file_names = len(
            duplicates
        )

        metrics.duplicate_file_name_list = sorted(
            duplicates
        )

        metrics.total_source_files = len(
            repository.source_files
        )

        if metrics.total_source_files:

            metrics.average_lines_per_file = (
                metrics.total_source_lines
                / metrics.total_source_files
            )

    def _analyse_file(
        self,
        file_path: Path,
        content: str,
        metrics: CodeMetrics,
    ) -> None:

        lines = content.splitlines()

        line_count = len(lines)

        relative = str(file_path)

        metrics.file_line_counts[
            relative
        ] = line_count

        metrics.total_source_lines += line_count

        if (
            metrics.smallest_file_lines == 0
            or line_count
            < metrics.smallest_file_lines
        ):
            metrics.smallest_file = relative
            metrics.smallest_file_lines = line_count

        if (
            line_count
            > metrics.largest_file_lines
        ):
            metrics.largest_file = relative
            metrics.largest_file_lines = line_count

        self._categorize_file_size(
            line_count,
            metrics,
        )

        self._analyse_lines(
            relative,
            lines,
            metrics,
        )

        lower = content.lower()

        generated_by_name = (
            file_path.name.endswith(".min.js")
            or file_path.name.endswith(".bundle.js")
        )

        generated_by_path = any(
            part.lower() in {
                "dist",
                "build",
                "generated",
                "vendor",
            }
            for part in file_path.parts
        )

        generated_by_header = any(
            keyword in lower[:500]
            for keyword in self.GENERATED_KEYWORDS
        )

        if (
            generated_by_name
            or generated_by_path
            or generated_by_header
        ):
            metrics.generated_files += 1

        if self._is_minified(content):
            metrics.minified_files += 1

    def _analyse_lines(
        self,
        relative_path: str,
        lines: list[str],
        metrics: CodeMetrics,
    ) -> None:

        comment_count = 0
        function_count = 0
        class_count = 0

        inside_block_comment = False

        for line in lines:

            stripped = line.strip()

            if not stripped:
                metrics.blank_lines += 1
                continue

            # ----------------------------------------------------------
            # Block comments
            # ----------------------------------------------------------

            if inside_block_comment:

                metrics.comment_lines += 1
                comment_count += 1

                if any(
                    end in stripped
                    for end in self.BLOCK_COMMENT_END
                ):
                    inside_block_comment = False

                continue

            if any(
                stripped.startswith(start)
                for start in self.BLOCK_COMMENT_START
            ):

                metrics.comment_lines += 1
                comment_count += 1

                metrics.documentation_comment_blocks += 1

                if not any(
                    stripped.endswith(end)
                    for end in self.BLOCK_COMMENT_END
                ):
                    inside_block_comment = True

                if (
                    stripped.startswith('"""')
                    or stripped.startswith("'''")
                ):
                    metrics.docstring_count += 1

                continue

            # ----------------------------------------------------------
            # Single line comments
            # ----------------------------------------------------------

            if stripped.startswith(
                self.COMMENT_PREFIXES
            ):

                metrics.comment_lines += 1
                comment_count += 1

                upper = stripped.upper()

                if "TODO" in upper:
                    metrics.todo_count += 1

                if "FIXME" in upper:
                    metrics.fixme_count += 1

                if "HACK" in upper:
                    metrics.hack_count += 1

                if "XXX" in upper:
                    metrics.xxx_count += 1

                continue

            # ----------------------------------------------------------
            # Code
            # ----------------------------------------------------------

            metrics.code_lines += 1

            if any(
                pattern.match(stripped)
                for pattern in self.CLASS_PATTERNS
            ):
                metrics.total_classes += 1
                class_count += 1

            if any(
                pattern.match(stripped)
                for pattern in self.FUNCTION_PATTERNS
            ):
                metrics.total_functions += 1
                function_count += 1

            if self.INTERFACE_PATTERN.match(stripped):
                metrics.total_interfaces += 1

            if self.ENUM_PATTERN.match(stripped):
                metrics.total_enums += 1

        metrics.file_comment_counts[
            relative_path
        ] = comment_count

        metrics.file_function_counts[
            relative_path
        ] = function_count

        metrics.file_class_counts[
            relative_path
        ] = class_count

    def _categorize_file_size(
        self,
        line_count: int,
        metrics: CodeMetrics,
    ) -> None:

        if line_count < 100:
            metrics.files_under_100_lines += 1

        elif line_count < 300:
            metrics.files_100_to_300_lines += 1

        elif line_count < 500:
            metrics.files_300_to_500_lines += 1

        elif line_count < 1000:
            metrics.files_over_500_lines += 1

        else:
            metrics.files_over_1000_lines += 1

    def _calculate_percentages(
        self,
        metrics: CodeMetrics,
    ) -> None:

        total = metrics.total_source_lines

        if total == 0:
            return

        metrics.code_line_percentage = (
            metrics.code_lines * 100
        ) / total

        metrics.blank_line_percentage = (
            metrics.blank_lines * 100
        ) / total

        metrics.comment_line_percentage = (
            metrics.comment_lines * 100
        ) / total

    @staticmethod
    def _is_minified(
        content: str,
    ) -> bool:

        if not content:
            return False

        lines = content.splitlines()

        if len(lines) > 5:
            return False

        longest = max(
            (len(line) for line in lines),
            default=0,
        )

        return longest > 1000

    